include(${CMAKE_CURRENT_LIST_DIR}/Generic-cortex-m-common.cmake)

set(CMAKE_ASM_FLAGS_DEBUG "-g3 -Og")
set(CMAKE_C_FLAGS_DEBUG "-g3 -Og")
set(CMAKE_CXX_FLAGS_DEBUG "-g3 -Og")

set(CMAKE_ASM_FLAGS_RELEASE "-O3")
set(CMAKE_C_FLAGS_RELEASE "-O3")
set(CMAKE_CXX_FLAGS_RELEASE "$-O3")

set(CMAKE_ASM_FLAGS_RELWITHDEBINFO "-O2 -g")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g")

set(CMAKE_ASM_FLAGS_MINSIZEREL "-Os -Wl,--gc-sections")
set(CMAKE_C_FLAGS_MINSIZEREL "-Os -Wl,--gc-sections")

set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT} --specs=nano.specs --specs=nosys.specs")
